// REDUX ACTION TYPES

export const GET_PROJECT_LIST_ERROR = 'GET_PROJECT_LIST_ERROR'
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS'
export const GET_PROJECT_LIST_LOADING = 'GET_PROJECT_LIST_LOADING'

export const LOADING = 'LOADING'
export const CLEAR_DATA = 'CLEAR_DATA'
